export const projects = [
    {
        id: 1,
        title: "STARTJAP",
        tag: "ML.NET / Web App",
        description: "Developed a web-based decision support system to assist students in selecting the most suitable internship programs in Japan based on their profiles and criteria.",
        tech: ["C#", "ML.NET", "ASP.NET", "SQL Server"],
        colSpan: "md:col-span-2",
        githubUrl: "http://startjap.runasp.net",
        demoUrl: "",
    },
    {
        id: 2,
        title: "ML.NET Hoax Detection",
        tag: "AI / Machine Learning",
        description: "A Hoax Detection application built using C# and the ML.NET framework. It utilizes Natural Language Processing (NLP) to classify text as either valid news or a hoax.",
        tech: ["C#", "ML.NET", "ASP.NET", "SQL Server"],
        colSpan: "md:col-span-1",
        githubUrl: "https://github.com/abdurrahmangofiky/ML.NET.Deteksi.Hoax.git",
        demoUrl: "",
    },
    {
        id: 3,
        title: "BPS Website Project",
        tag: "Internal System",
        description: "Developed the frontend interface for the 'Organizational Culture Survey' (Survei Budaya Organisasi) application, aiming to automate and digitize the internal employee survey process.",
        tech: ["Laravel", "MySQL", "Bootstrap"],
        colSpan: "md:col-span-1",
        githubUrl: "https://github.com/abdurrahmangofiky/Proyek-Website-BPS.git",
        demoUrl: "",
    },
    {
        id: 4,
        title: "Chatbot Fish Disease Diagnosis",
        tag: "Python / NLP",
        description: "Developed a multi-modal chatbot capable of diagnosing fish diseases through both text descriptions and image inputs.",
        tech: ["Python", "Flask", "NLP"],
        colSpan: "md:col-span-2",
        githubUrl: "https://github.com/abdurrahmangofiky/Fish-Disease-Diagnosis.git",
        demoUrl: "",
    },
];
